"use client";

import React from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft } from "../../Helpers/icons";

const TermsAndConditionsPage = () => {
  const router = useRouter();

  return (
    <div className="w-full min-h-screen bg-(--color-main) flex flex-col">
      {/* Header */}
      <div className="w-full px-6 py-5 flex items-center gap-4 border-b border-gray-300 dark:border-gray-700 bg-(--color-secondary)/40">
        <button
          onClick={() => router.back()}
          className="p-2 rounded-lg hover:bg-black/10 dark:hover:bg-white/10 transition cursor-pointer text-(--text-normal)"
        >
          <ArrowLeft size={18} />
        </button>
        <h1 className="text-2xl font-bold text-(--text-normal) tracking-tight">
          Settings / Terms & Conditions
        </h1>
      </div>

      {/* Content */}
      <div className="w-full max-w-2xl mx-auto px-6 py-8 flex flex-col gap-6">
        <p className="text-(--text-normal)/80 text-sm leading-relaxed">
          <span className="font-semibold">Last updated:</span> April 14, 2026
        </p>

        <div className="flex flex-col gap-6 text-(--text-normal)/70 text-sm leading-relaxed">
          <section className="flex flex-col gap-2">
            <h2 className="text-lg font-bold text-(--text-normal)">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing and using ArchiText, you agree to be bound by these
              Terms and Conditions. If you do not agree with any part of these
              terms, you must not use our service.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-lg font-bold text-(--text-normal)">
              2. Use of Service
            </h2>
            <p>
              ArchiText provides AI-powered software architecture generation
              tools. You may use the service for personal and commercial
              projects, subject to these terms. You are responsible for all
              activity under your account.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-lg font-bold text-(--text-normal)">
              3. User Content
            </h2>
            <p>
              You retain ownership of any content you submit to ArchiText,
              including project descriptions and conversation data. By using our
              service, you grant us a limited license to process this content
              through our AI systems to provide the service.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-lg font-bold text-(--text-normal)">
              4. AI-Generated Content
            </h2>
            <p>
              Architecture suggestions and outputs generated by the AI are
              provided as-is and should be reviewed before use in production
              environments. ArchiText is not responsible for any issues arising
              from the direct use of AI-generated architectures.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-lg font-bold text-(--text-normal)">
              5. Account Termination
            </h2>
            <p>
              We reserve the right to suspend or terminate your account if you
              violate these terms. You may also delete your account at any time
              through the Data Controls section in your settings.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-lg font-bold text-(--text-normal)">
              6. Limitation of Liability
            </h2>
            <p>
              ArchiText shall not be liable for any indirect, incidental, or
              consequential damages arising from the use or inability to use the
              service. Our total liability shall not exceed the amount you paid
              for the service.
            </p>
          </section>

          <section className="flex flex-col gap-2">
            <h2 className="text-lg font-bold text-(--text-normal)">
              7. Changes to Terms
            </h2>
            <p>
              We may update these terms from time to time. Continued use of the
              service after changes constitutes acceptance of the updated terms.
              We will notify you of significant changes via email or in-app
              notification.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditionsPage;
